import pandas as pd

# Mappings
BIOMES = {
    492: "root:Mixed",
    491: "root:Control",
    490: "root:Host-associated:Tunicates:Ascidians",
    489: "root:Host-associated:Tunicates",
    488: "root:Host-associated:Spiralia",
    487: "root:Host-associated:Reptile:Oral cavity:Venom gland:Venom",
    486: "root:Host-associated:Reptile:Oral cavity:Venom gland",
    485: "root:Host-associated:Reptile:Oral cavity",
    484: "root:Host-associated:Reptile",
    483: "root:Host-associated:Protozoa",
    482: "root:Host-associated:Protists",
    481: "root:Host-associated:Porifera",
    480: "root:Host-associated:Plants:Root",
    479: "root:Host-associated:Plants:Rhizosphere:Forest soil",
    478: "root:Host-associated:Plants:Rhizosphere:Soil",
    477: "root:Host-associated:Plants:Rhizosphere:Epiphytes",
    476: "root:Host-associated:Plants:Rhizosphere",
    475: "root:Host-associated:Plants:Rhizoplane:Soil",
    474: "root:Host-associated:Plants:Rhizoplane:Epiphytes",
    473: "root:Host-associated:Plants:Rhizoplane:Endophytes",
    472: "root:Host-associated:Plants:Rhizoplane",
    471: "root:Host-associated:Plants:Rhizome:Epiphytes",
    470: "root:Host-associated:Plants:Rhizome",
    469: "root:Host-associated:Plants:Phylloplane:Epiphytes",
    468: "root:Host-associated:Plants:Phylloplane:Endophytes",
    467: "root:Host-associated:Plants:Phylloplane",
    466: "root:Host-associated:Plants",
    465: "root:Host-associated:Mollusca:Shell",
    464: "root:Host-associated:Mollusca:Respiratory system:Gills:Intracellular",
    463: "root:Host-associated:Mollusca:Respiratory system:Gills:Extracellular",
    462: "root:Host-associated:Mollusca:Respiratory system:Gills",
    461: "root:Host-associated:Mollusca:Respiratory system",
    460: "root:Host-associated:Mollusca:Digestive system:Glands",
    459: "root:Host-associated:Mollusca:Digestive system:Ceca:Uncharacterized",
    458: "root:Host-associated:Mollusca:Digestive system:Ceca",
    457: "root:Host-associated:Mollusca:Digestive system",
    456: "root:Host-associated:Mollusca",
    455: "root:Host-associated:Microbial:Dinoflagellates:Endosymbionts",
    454: "root:Host-associated:Microbial:Dinoflagellates",
    453: "root:Host-associated:Microbial:Bacteria",
    452: "root:Host-associated:Microbial",
    451: "root:Host-associated:Mammals:Skin",
    450: "root:Host-associated:Mammals:Respiratory system:Pulmonary system:Viriome",
    449: "root:Host-associated:Mammals:Respiratory system:Pulmonary system",
    448: "root:Host-associated:Mammals:Respiratory system:Nasopharyngeal:Nasal cavity",
    447: "root:Host-associated:Mammals:Respiratory system:Nasopharyngeal",
    446: "root:Host-associated:Mammals:Respiratory system",
    445: "root:Host-associated:Mammals:Reproductive system",
    444: "root:Host-associated:Mammals:Nervous system:Brain",
    443: "root:Host-associated:Mammals:Nervous system",
    442: "root:Host-associated:Mammals:Milk",
    441: "root:Host-associated:Mammals:Lymphatic:Lymph nodes",
    440: "root:Host-associated:Mammals:Lymphatic",
    439: "root:Host-associated:Mammals:Gastrointestinal tract:Intestine:Fecal",
    438: "root:Host-associated:Mammals:Gastrointestinal tract:Intestine",
    437: "root:Host-associated:Mammals:Gastrointestinal tract",
    436: "root:Host-associated:Mammals:Excretory system:Urine",
    435: "root:Host-associated:Mammals:Excretory system",
    434: "root:Host-associated:Mammals:Digestive system:Stomach:Rumen",
    433: "root:Host-associated:Mammals:Digestive system:Stomach:Endoperitrophic space",
    432: "root:Host-associated:Mammals:Digestive system:Stomach",
    431: "root:Host-associated:Mammals:Digestive system:Oral cavity:Buccal mucosa",
    430: "root:Host-associated:Mammals:Digestive system:Oral cavity",
    429: "root:Host-associated:Mammals:Digestive system:Midgut",
    428: "root:Host-associated:Mammals:Digestive system:Large intestine:Fecal",
    427: "root:Host-associated:Mammals:Digestive system:Large intestine:Cecum",
    426: "root:Host-associated:Mammals:Digestive system:Large intestine",
    425: "root:Host-associated:Mammals:Digestive system:Foregut:Rumen",
    424: "root:Host-associated:Mammals:Digestive system:Foregut",
    423: "root:Host-associated:Mammals:Digestive system:Fecal:Uncharacterized",
    422: "root:Host-associated:Mammals:Digestive system:Fecal",
    421: "root:Host-associated:Mammals:Digestive system",
    420: "root:Host-associated:Mammals:Circulatory system:Blood",
    419: "root:Host-associated:Mammals:Circulatory system",
    418: "root:Host-associated:Mammals",
    417: "root:Host-associated:Invertebrates:Echinodermata:Sea Urchin",
    416: "root:Host-associated:Invertebrates:Echinodermata",
    415: "root:Host-associated:Invertebrates:Cnidaria:Coral",
    414: "root:Host-associated:Invertebrates:Cnidaria",
    413: "root:Host-associated:Invertebrates:Bryozoans:Gymnolaemates",
    412: "root:Host-associated:Invertebrates:Bryozoans",
    411: "root:Host-associated:Invertebrates",
    410: "root:Host-associated:Insecta:Digestive system",
    409: "root:Host-associated:Insecta",
    408: "root:Host-associated:Human:Skin:Volar forearm",
    407: "root:Host-associated:Human:Skin:Umbilicus",
    406: "root:Host-associated:Human:Skin:retroauricular crease",
    405: "root:Host-associated:Human:Skin:Naris",
    404: "root:Host-associated:Human:Skin:Medial distal leg:Venous leg ulcers",
    403: "root:Host-associated:Human:Skin:Medial distal leg",
    402: "root:Host-associated:Human:Skin:Axilla",
    401: "root:Host-associated:Human:Skin",
    400: "root:Host-associated:Human:Respiratory system:Pulmonary system:Viriome",
    399: "root:Host-associated:Human:Respiratory system:Pulmonary system:Trachea",
    398: "root:Host-associated:Human:Respiratory system:Pulmonary system:Sputum",
    397: "root:Host-associated:Human:Respiratory system:Pulmonary system:Lung",
    396: "root:Host-associated:Human:Respiratory system:Pulmonary system",
    395: "root:Host-associated:Human:Respiratory system:Nasopharyngeal:Pharynx",
    394: "root:Host-associated:Human:Respiratory system:Nasopharyngeal:Nasal cavity",
    393: "root:Host-associated:Human:Respiratory system:Nasopharyngeal:anterior nares",
    392: "root:Host-associated:Human:Respiratory system:Nasopharyngeal",
    391: "root:Host-associated:Human:Respiratory system",
    390: "root:Host-associated:Human:Reproductive system:Vagina:posterior fornix",
    389: "root:Host-associated:Human:Reproductive system:Vagina:Midpoint vagina",
    388: "root:Host-associated:Human:Reproductive system:Vagina:Introitus",
    387: "root:Host-associated:Human:Reproductive system:Vagina",
    386: "root:Host-associated:Human:Reproductive system:Female",
    385: "root:Host-associated:Human:Reproductive system",
    384: "root:Host-associated:Human:Nervous system:Cerebrospinal fluid",
    383: "root:Host-associated:Human:Nervous system",
    382: "root:Host-associated:Human:Milk",
    381: "root:Host-associated:Human:Lympathic system:Lymph nodes",
    380: "root:Host-associated:Human:Lympathic system",
    379: "root:Host-associated:Human:Fossil:Bone",
    378: "root:Host-associated:Human:Fossil",
    377: "root:Host-associated:Human:Excretory system:Urethra:Urine",
    376: "root:Host-associated:Human:Excretory system:Urethra",
    375: "root:Host-associated:Human:Excretory system",
    374: "root:Host-associated:Human:Digestive system:Oral:tongue dorsum",
    373: "root:Host-associated:Human:Digestive system:Oral:Throat",
    372: "root:Host-associated:Human:Digestive system:Oral:Supragingival plaque",
    370: "root:Host-associated:Human:Digestive system:Oral:Subgingival plaque",
    369: "root:Host-associated:Human:Digestive system:Oral:Saliva",
    368: "root:Host-associated:Human:Digestive system:Oral:Periodontal pockets",
    367: "root:Host-associated:Human:Digestive system:Oral:Palatine tonsils",
    366: "root:Host-associated:Human:Digestive system:Oral:hard palate",
    365: "root:Host-associated:Human:Digestive system:Oral:buccal mucosa",
    364: "root:Host-associated:Human:Digestive system:Oral:Attached Keratinized gingiva",
    363: "root:Host-associated:Human:Digestive system:Oral",
    362: "root:Host-associated:Human:Digestive system:Large intestine:Sigmoid colon",
    361: "root:Host-associated:Human:Digestive system:Large intestine:Fecal",
    360: "root:Host-associated:Human:Digestive system:Large intestine",
    359: "root:Host-associated:Human:Digestive system:Intestine",
    358: "root:Host-associated:Human:Digestive system:Hindgut:Rectum",
    357: "root:Host-associated:Human:Digestive system:Hindgut",
    356: "root:Host-associated:Human:Digestive system",
    355: "root:Host-associated:Human:Circulatory system:Blood",
    354: "root:Host-associated:Human:Circulatory system",
    353: "root:Host-associated:Human",
    352: "root:Host-associated:Fungi",
    351: "root:Host-associated:Fish:Skin:Slime",
    350: "root:Host-associated:Fish:Skin",
    349: "root:Host-associated:Fish:Reproductive system",
    348: "root:Host-associated:Fish:Excretory system:Kidneys",
    347: "root:Host-associated:Fish:Excretory system",
    346: "root:Host-associated:Fish:Digestive system:Intestine",
    345: "root:Host-associated:Fish:Digestive system:Foregut:Uncharacterized",
    344: "root:Host-associated:Fish:Digestive system:Foregut",
    343: "root:Host-associated:Fish:Digestive system",
    342: "root:Host-associated:Fish:Circulatory system:Blood",
    341: "root:Host-associated:Fish:Circulatory system",
    340: "root:Host-associated:Fish",
    339: "root:Host-associated:Endosymbionts:Fungi:Endosymbionts",
    338: "root:Host-associated:Endosymbionts:Fungi",
    337: "root:Host-associated:Endosymbionts",
    336: "root:Host-associated:Echinodermata",
    335: "root:Host-associated:Cnidaria",
    334: "root:Host-associated:Birds:Respiratory system:Lungs",
    333: "root:Host-associated:Birds:Respiratory system",
    332: "root:Host-associated:Birds:Reproductive system",
    331: "root:Host-associated:Birds:Digestive system:Small intestine:Duodenal",
    330: "root:Host-associated:Birds:Digestive system:Small intestine",
    329: "root:Host-associated:Birds:Digestive system:Fecal",
    328: "root:Host-associated:Birds:Digestive system:Digestive tube:Cecum",
    327: "root:Host-associated:Birds:Digestive system:Digestive tube",
    326: "root:Host-associated:Birds:Digestive system:Crop:Lumen",
    325: "root:Host-associated:Birds:Digestive system:Crop",
    324: "root:Host-associated:Birds:Digestive system:Ceca:Lumen",
    323: "root:Host-associated:Birds:Digestive system:Ceca",
    322: "root:Host-associated:Birds:Digestive system",
    321: "root:Host-associated:Birds:Circulatory system:Blood",
    320: "root:Host-associated:Birds:Circulatory system",
    319: "root:Host-associated:Birds",
    318: "root:Host-associated:Arthropoda:Venom gland:Venom",
    317: "root:Host-associated:Arthropoda:Venom gland",
    316: "root:Host-associated:Arthropoda:Symbiotic fungal gardens and galleries:Fungus garden:Garden dump",
    315: "root:Host-associated:Arthropoda:Symbiotic fungal gardens and galleries:Fungus garden",
    314: "root:Host-associated:Arthropoda:Symbiotic fungal gardens and galleries:Fungus gallery",
    313: "root:Host-associated:Arthropoda:Symbiotic fungal gardens and galleries",
    312: "root:Host-associated:Arthropoda:Respiratory system:Gills",
    311: "root:Host-associated:Arthropoda:Respiratory system",
    310: "root:Host-associated:Arthropoda:Oral cavity",
    309: "root:Host-associated:Arthropoda:Intracellular endosymbionts:Secondary",
    308: "root:Host-associated:Arthropoda:Intracellular endosymbionts:Primary:Bacteriomes",
    307: "root:Host-associated:Arthropoda:Intracellular endosymbionts:Primary",
    306: "root:Host-associated:Arthropoda:Intracellular endosymbionts",
    305: "root:Host-associated:Arthropoda:Integument:Cuticle:Thoracic segments",
    304: "root:Host-associated:Arthropoda:Integument:Cuticle",
    303: "root:Host-associated:Arthropoda:Integument",
    302: "root:Host-associated:Arthropoda:Digestive system:Oral:Saliva",
    301: "root:Host-associated:Arthropoda:Digestive system:Oral",
    300: "root:Host-associated:Arthropoda:Digestive system:Midgut",
    299: "root:Host-associated:Arthropoda:Digestive system:Hindgut:P3 segment",
    298: "root:Host-associated:Arthropoda:Digestive system:Hindgut:P1 segment",
    297: "root:Host-associated:Arthropoda:Digestive system:Hindgut",
    296: "root:Host-associated:Arthropoda:Digestive system:Gut:Proctodeal segment",
    295: "root:Host-associated:Arthropoda:Digestive system:Gut:P3 segment",
    294: "root:Host-associated:Arthropoda:Digestive system:Gut",
    293: "root:Host-associated:Arthropoda:Digestive system:Foregut",
    292: "root:Host-associated:Arthropoda:Digestive system",
    291: "root:Host-associated:Arthropoda",
    290: "root:Host-associated:Annelida:Reproductive system:Egg capsule:Extracellular",
    289: "root:Host-associated:Annelida:Reproductive system:Egg capsule",
    288: "root:Host-associated:Annelida:Reproductive system",
    287: "root:Host-associated:Annelida:Intracellular endosymbionts:Trophosome",
    286: "root:Host-associated:Annelida:Intracellular endosymbionts",
    285: "root:Host-associated:Annelida:Integument:Subcuticular space:Extracellular symbionts",
    284: "root:Host-associated:Annelida:Integument:Subcuticular space",
    283: "root:Host-associated:Annelida:Integument:Cuticle:Epibionts",
    282: "root:Host-associated:Annelida:Integument:Cuticle",
    281: "root:Host-associated:Annelida:Integument",
    280: "root:Host-associated:Annelida:Digestive system:Digestive tube:Extracellular symbionts",
    279: "root:Host-associated:Annelida:Digestive system:Digestive tube",
    278: "root:Host-associated:Annelida:Digestive system",
    277: "root:Host-associated:Annelida",
    276: "root:Host-associated:Animal:Skin",
    275: "root:Host-associated:Animal:Respiratory system",
    274: "root:Host-associated:Animal:Reproductive system",
    273: "root:Host-associated:Animal:Fossil:Feces",
    272: "root:Host-associated:Animal:Fossil:Bone",
    271: "root:Host-associated:Animal:Fossil",
    270: "root:Host-associated:Animal:Digestive system:Fecal",
    269: "root:Host-associated:Animal:Digestive system",
    268: "root:Host-associated:Animal:Circulatory system",
    267: "root:Host-associated:Animal",
    266: "root:Host-associated:Amphibia:Excretory system",
    265: "root:Host-associated:Amphibia:Digestive system",
    264: "root:Host-associated:Amphibia",
    263: "root:Host-associated:Algae:Red algae:Ectosymbionts",
    262: "root:Host-associated:Algae:Red algae",
    261: "root:Host-associated:Algae:Green algae:Ectosymbionts",
    260: "root:Host-associated:Algae:Green algae",
    259: "root:Host-associated:Algae:Brown Algae",
    258: "root:Host-associated:Algae",
    257: "root:Host-associated",
    256: "root:Environmental:Terrestrial:Volcanic:Fumaroles",
    255: "root:Environmental:Terrestrial:Volcanic",
    254: "root:Environmental:Terrestrial:Soil:Wetlands:Permafrost",
    253: "root:Environmental:Terrestrial:Soil:Wetlands",
    252: "root:Environmental:Terrestrial:Soil:Viriome",
    251: "root:Environmental:Terrestrial:Soil:Uranium contaminated",
    250: "root:Environmental:Terrestrial:Soil:Tropical rainforest",
    249: "root:Environmental:Terrestrial:Soil:Shrubland",
    248: "root:Environmental:Terrestrial:Soil:Permafrost",
    247: "root:Environmental:Terrestrial:Soil:Oil-contaminated",
    246: "root:Environmental:Terrestrial:Soil:Mine drainage",
    245: "root:Environmental:Terrestrial:Soil:Mine",
    244: "root:Environmental:Terrestrial:Soil:Grasslands",
    243: "root:Environmental:Terrestrial:Soil:Forest soil",
    242: "root:Environmental:Terrestrial:Soil:Desert",
    241: "root:Environmental:Terrestrial:Soil:Contaminated",
    240: "root:Environmental:Terrestrial:Soil:Boreal forest",
    239: "root:Environmental:Terrestrial:Soil:Agricultural",
    238: "root:Environmental:Terrestrial:Soil:Silt",
    237: "root:Environmental:Terrestrial:Soil:Sand:Oil-contaminated",
    236: "root:Environmental:Terrestrial:Soil:Sand:Grasslands",
    235: "root:Environmental:Terrestrial:Soil:Sand:Forest soil",
    234: "root:Environmental:Terrestrial:Soil:Sand:Desert",
    233: "root:Environmental:Terrestrial:Soil:Sand",
    232: "root:Environmental:Terrestrial:Soil:Loam:Grasslands",
    231: "root:Environmental:Terrestrial:Soil:Loam:Forest soil",
    230: "root:Environmental:Terrestrial:Soil:Loam:Contaminated",
    229: "root:Environmental:Terrestrial:Soil:Loam:Agricultural",
    228: "root:Environmental:Terrestrial:Soil:Loam",
    227: "root:Environmental:Terrestrial:Soil:Crop:Agricultural land",
    226: "root:Environmental:Terrestrial:Soil:Crop",
    225: "root:Environmental:Terrestrial:Soil:Clay:Oil-contaminated",
    224: "root:Environmental:Terrestrial:Soil:Clay:Grasslands",
    223: "root:Environmental:Terrestrial:Soil:Clay:Contaminated",
    222: "root:Environmental:Terrestrial:Soil:Clay:Agricultural land",
    221: "root:Environmental:Terrestrial:Soil:Clay",
    220: "root:Environmental:Terrestrial:Soil",
    219: "root:Environmental:Terrestrial:Rock-dwelling (subaerial biofilm)",
    218: "root:Environmental:Terrestrial:Oil reservoir",
    217: "root:Environmental:Terrestrial:Geologic:Mine",
    216: "root:Environmental:Terrestrial:Geologic",
    215: "root:Environmental:Terrestrial:Deep subsurface:Clay",
    214: "root:Environmental:Terrestrial:Deep subsurface",
    213: "root:Environmental:Terrestrial:Asphalt lakes:Tar",
    212: "root:Environmental:Terrestrial:Asphalt lakes",
    211: "root:Environmental:Terrestrial:Agricultural field",
    210: "root:Environmental:Terrestrial",
    209: "root:Environmental:Aquatic:Thermal springs:Warm (34-42C):Sediment",
    208: "root:Environmental:Aquatic:Thermal springs:Warm (34-42C):Neutral",
    207: "root:Environmental:Aquatic:Thermal springs:Warm (34-42C)",
    206: "root:Environmental:Aquatic:Thermal springs:Tepid (25-34C):Sediment",
    205: "root:Environmental:Aquatic:Thermal springs:Tepid (25-34C)",
    204: "root:Environmental:Aquatic:Thermal springs:Sediment",
    203: "root:Environmental:Aquatic:Thermal springs:Near-boiling (>90C):Alkaline",
    202: "root:Environmental:Aquatic:Thermal springs:Near-boiling (>90C)",
    201: "root:Environmental:Aquatic:Thermal springs:Hot (42-90C):Sediment",
    200: "root:Environmental:Aquatic:Thermal springs:Hot (42-90C):Neutral",
    199: "root:Environmental:Aquatic:Thermal springs:Hot (42-90C):Alkaline",
    198: "root:Environmental:Aquatic:Thermal springs:Hot (42-90C):Acidic",
    197: "root:Environmental:Aquatic:Thermal springs:Hot (42-90C)",
    196: "root:Environmental:Aquatic:Thermal springs",
    195: "root:Environmental:Aquatic:Sediment",
    194: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Salt crystallizer pond:Microbial mats",
    193: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Salt crystallizer pond",
    192: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Thalassic",
    191: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Sediment",
    190: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Microbial mats",
    189: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Hypolimnion",
    188: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Epilimnion",
    187: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Athalassic",
    186: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline",
    185: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Near-boiling (>90C):Alkaline",
    184: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Near-boiling (>90C)",
    183: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Hypersaline:Sediment",
    182: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Hypersaline:Microbial mats",
    181: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Hypersaline",
    180: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Alkaline:Sediment",
    179: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Alkaline:Microbial mats",
    178: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Alkaline:Carbonate",
    177: "root:Environmental:Aquatic:Non-marine Saline and Alkaline:Alkaline",
    176: "root:Environmental:Aquatic:Non-marine Saline and Alkaline",
    175: "root:Environmental:Aquatic:Meromictic lake",
    174: "root:Environmental:Aquatic:Marine:Wetlands:Sediment",
    173: "root:Environmental:Aquatic:Marine:Wetlands",
    172: "root:Environmental:Aquatic:Marine:Volcanic",
    171: "root:Environmental:Aquatic:Marine:Sediment",
    170: "root:Environmental:Aquatic:Marine:Oil-contaminated sediment",
    169: "root:Environmental:Aquatic:Marine:Pelagic",
    168: "root:Environmental:Aquatic:Marine:Oil seeps",
    167: "root:Environmental:Aquatic:Marine:Oil field:bore hole",
    166: "root:Environmental:Aquatic:Marine:Oil field",
    165: "root:Environmental:Aquatic:Marine:Oceanic:Sediment",
    164: "root:Environmental:Aquatic:Marine:Oceanic:Photic zone",
    163: "root:Environmental:Aquatic:Marine:Oceanic:Oil-contaminated sediments",
    162: "root:Environmental:Aquatic:Marine:Oceanic:Oil-contaminated",
    161: "root:Environmental:Aquatic:Marine:Oceanic:Benthic",
    160: "root:Environmental:Aquatic:Marine:Oceanic:Aphotic zone",
    159: "root:Environmental:Aquatic:Marine:Oceanic:Abyssal plane",
    158: "root:Environmental:Aquatic:Marine:Oceanic",
    157: "root:Environmental:Aquatic:Marine:Neritic zone:Sediment",
    156: "root:Environmental:Aquatic:Marine:Neritic zone:Oil-contaminated sediment",
    155: "root:Environmental:Aquatic:Marine:Neritic zone",
    154: "root:Environmental:Aquatic:Marine:Marginal Sea",
    153: "root:Environmental:Aquatic:Marine:Intertidal zone:Sediment",
    152: "root:Environmental:Aquatic:Marine:Intertidal zone:Salt marsh",
    151: "root:Environmental:Aquatic:Marine:Intertidal zone:Oil-contaminated",
    150: "root:Environmental:Aquatic:Marine:Intertidal zone:Microbialites",
    149: "root:Environmental:Aquatic:Marine:Intertidal zone:Mangrove swamp",
    148: "root:Environmental:Aquatic:Marine:Intertidal zone:Estuary",
    147: "root:Environmental:Aquatic:Marine:Intertidal zone:Coral reef",
    146: "root:Environmental:Aquatic:Marine:Intertidal zone:Beach",
    145: "root:Environmental:Aquatic:Marine:Intertidal zone",
    144: "root:Environmental:Aquatic:Marine:Hydrothermal vents:Sediment",
    143: "root:Environmental:Aquatic:Marine:Hydrothermal vents:Microbial mats",
    142: "root:Environmental:Aquatic:Marine:Hydrothermal vents:Diffuse flow",
    141: "root:Environmental:Aquatic:Marine:Hydrothermal vents:Black smokers",
    140: "root:Environmental:Aquatic:Marine:Hydrothermal vents",
    139: "root:Environmental:Aquatic:Marine:Fossil:Whale fall",
    138: "root:Environmental:Aquatic:Marine:Fossil",
    137: "root:Environmental:Aquatic:Marine:Cold seeps:Sediment",
    136: "root:Environmental:Aquatic:Marine:Cold seeps",
    135: "root:Environmental:Aquatic:Marine:Coastal:Sediment",
    134: "root:Environmental:Aquatic:Marine:Coastal",
    133: "root:Environmental:Aquatic:Marine:Brackish",
    132: "root:Environmental:Aquatic:Marine",
    131: "root:Environmental:Aquatic:Lentic:Brackish",
    130: "root:Environmental:Aquatic:Lentic",
    129: "root:Environmental:Aquatic:Freshwater:Wetlands:Swamp",
    128: "root:Environmental:Aquatic:Freshwater:Wetlands:Sediment",
    127: "root:Environmental:Aquatic:Freshwater:Wetlands:Marsh",
    126: "root:Environmental:Aquatic:Freshwater:Wetlands:Bog",
    125: "root:Environmental:Aquatic:Freshwater:Wetlands",
    124: "root:Environmental:Aquatic:Freshwater:Subglacial lake",
    123: "root:Environmental:Aquatic:Freshwater:Storm water:Drainage pipe biofilm",
    122: "root:Environmental:Aquatic:Freshwater:Storm water",
    121: "root:Environmental:Aquatic:Freshwater:Sediment",
    120: "root:Environmental:Aquatic:Freshwater:Pond:Sediment",
    119: "root:Environmental:Aquatic:Freshwater:Pond",
    118: "root:Environmental:Aquatic:Freshwater:Microbialites",
    117: "root:Environmental:Aquatic:Freshwater:Lotic:Sediment",
    116: "root:Environmental:Aquatic:Freshwater:Lotic:Mid stream",
    115: "root:Environmental:Aquatic:Freshwater:Lotic:Microbial mats",
    114: "root:Environmental:Aquatic:Freshwater:Lotic:Low land river systems",
    113: "root:Environmental:Aquatic:Freshwater:Lotic:Acidic",
    112: "root:Environmental:Aquatic:Freshwater:Lotic",
    111: "root:Environmental:Aquatic:Freshwater:Lentic:Sediment",
    110: "root:Environmental:Aquatic:Freshwater:Lentic:Littoral zone",
    109: "root:Environmental:Aquatic:Freshwater:Lentic:Limnetic zone",
    108: "root:Environmental:Aquatic:Freshwater:Lentic:Hypolimnion",
    107: "root:Environmental:Aquatic:Freshwater:Lentic:Epilimnion",
    106: "root:Environmental:Aquatic:Freshwater:Lentic",
    105: "root:Environmental:Aquatic:Freshwater:Lake",
    104: "root:Environmental:Aquatic:Freshwater:Ice:Ice accretions",
    103: "root:Environmental:Aquatic:Freshwater:Ice:Glacier",
    102: "root:Environmental:Aquatic:Freshwater:Ice:Glacial lake",
    101: "root:Environmental:Aquatic:Freshwater:Ice",
    100: "root:Environmental:Aquatic:Freshwater:Groundwater:Mine drainage",
    99: "root:Environmental:Aquatic:Freshwater:Groundwater:Mine",
    98: "root:Environmental:Aquatic:Freshwater:Groundwater:Contaminated",
    97: "root:Environmental:Aquatic:Freshwater:Groundwater:Coalbed water",
    96: "root:Environmental:Aquatic:Freshwater:Groundwater:Cave water",
    95: "root:Environmental:Aquatic:Freshwater:Groundwater:Biofilm",
    94: "root:Environmental:Aquatic:Freshwater:Groundwater:Acid Mine Drainage",
    93: "root:Environmental:Aquatic:Freshwater:Groundwater",
    92: "root:Environmental:Aquatic:Freshwater:Drinking water:Delivery networks",
    91: "root:Environmental:Aquatic:Freshwater:Drinking water:Chlorinated",
    90: "root:Environmental:Aquatic:Freshwater:Drinking water",
    89: "root:Environmental:Aquatic:Freshwater",
    88: "root:Environmental:Aquatic:Estuary:Sediment",
    87: "root:Environmental:Aquatic:Estuary",
    86: "root:Environmental:Aquatic:Aquaculture",
    85: "root:Environmental:Aquatic",
    84: "root:Environmental:Air:Outdoor Air",
    83: "root:Environmental:Air:Indoor Air",
    82: "root:Environmental:Air",
    81: "root:Environmental",
    80: "root:Engineered:Wastewater:Water and sludge",
    79: "root:Engineered:Wastewater:Nutrient removal:Nitrogen removal:Anammox",
    78: "root:Engineered:Wastewater:Nutrient removal:Nitrogen removal",
    77: "root:Engineered:Wastewater:Nutrient removal:Dissolved organics (anaerobic):Activated sludge",
    76: "root:Engineered:Wastewater:Nutrient removal:Dissolved organics (anaerobic)",
    75: "root:Engineered:Wastewater:Nutrient removal:Dissolved organics (aerobic):Activated sludge",
    74: "root:Engineered:Wastewater:Nutrient removal:Dissolved organics (aerobic)",
    73: "root:Engineered:Wastewater:Nutrient removal:Biological phosphorus removal:Bioreactor",
    72: "root:Engineered:Wastewater:Nutrient removal:Biological phosphorus removal:Activated sludge",
    71: "root:Engineered:Wastewater:Nutrient removal:Biological phosphorus removal",
    70: "root:Engineered:Wastewater:Nutrient removal",
    69: "root:Engineered:Wastewater:Industrial wastewater:Pulp and paper wastewater",
    68: "root:Engineered:Wastewater:Industrial wastewater:Petrochemical",
    67: "root:Engineered:Wastewater:Industrial wastewater:Mine water",
    66: "root:Engineered:Wastewater:Industrial wastewater:Landfill leachate",
    65: "root:Engineered:Wastewater:Industrial wastewater:Agricultural wastewater",
    64: "root:Engineered:Wastewater:Industrial wastewater",
    63: "root:Engineered:Wastewater:Activated Sludge",
    62: "root:Engineered:Wastewater",
    61: "root:Engineered:Solid waste:Solid animal waste",
    60: "root:Engineered:Solid waste:Landfill",
    59: "root:Engineered:Solid waste:Composting:Wood:Bioreactor",
    58: "root:Engineered:Solid waste:Composting:Wood",
    57: "root:Engineered:Solid waste:Composting:Bioreactor",
    56: "root:Engineered:Solid waste:Composting:Grass:Bioreactor",
    55: "root:Engineered:Solid waste:Composting:Grass",
    54: "root:Engineered:Solid waste:Composting",
    53: "root:Engineered:Solid waste",
    52: "root:Engineered:Modeled:Simulated communities (sequence read mixture):Sanger",
    51: "root:Engineered:Modeled:Simulated communities (sequence read mixture)",
    50: "root:Engineered:Modeled:Simulated communities (microbial mixture)",
    49: "root:Engineered:Modeled:Simulated communities (DNA mixture)",
    48: "root:Engineered:Modeled",
    47: "root:Engineered:Lab Synthesis:Genetic cross",
    46: "root:Engineered:Lab Synthesis",
    45: "root:Engineered:Lab enrichment:Undefined media",
    44: "root:Engineered:Lab enrichment:Defined media:Marine media:Algoconsortia",
    43: "root:Engineered:Lab enrichment:Defined media:Marine media",
    42: "root:Engineered:Lab enrichment:Defined media:Anaerobic media",
    41: "root:Engineered:Lab enrichment:Defined media:Aerobic media",
    40: "root:Engineered:Lab enrichment:Defined media",
    39: "root:Engineered:Lab enrichment",
    38: "root:Engineered:Industrial production:Engineered product",
    37: "root:Engineered:Industrial production",
    36: "root:Engineered:Food production:Silage fermentation",
    35: "root:Engineered:Food production:Fermented vegetables",
    34: "root:Engineered:Food production:Fermented seafood",
    33: "root:Engineered:Food production:Fermented beverages",
    32: "root:Engineered:Food production:Dairy products",
    31: "root:Engineered:Food production",
    30: "root:Engineered:Built environment",
    29: "root:Engineered:Biotransformation:Mixed alcohol bioreactor",
    28: "root:Engineered:Biotransformation:Microbial solubilization of coal",
    27: "root:Engineered:Biotransformation:Microbial enhanced oil recovery",
    26: "root:Engineered:Biotransformation",
    25: "root:Engineered:Bioremediation:Tetrachloroethylene and derivatives:Tetrachloroethylene:Bioreactor",
    24: "root:Engineered:Bioremediation:Tetrachloroethylene and derivatives:Tetrachloroethylene",
    23: "root:Engineered:Bioremediation:Tetrachloroethylene and derivatives:Chloroethene:Bioreactor",
    22: "root:Engineered:Bioremediation:Tetrachloroethylene and derivatives:Chloroethene",
    21: "root:Engineered:Bioremediation:Tetrachloroethylene and derivatives",
    20: "root:Engineered:Bioremediation:Terephthalate:Wastewater:Bioreactor",
    19: "root:Engineered:Bioremediation:Terephthalate:Wastewater:Activated sludge",
    18: "root:Engineered:Bioremediation:Terephthalate:Wastewater",
    17: "root:Engineered:Bioremediation:Terephthalate",
    16: "root:Engineered:Bioremediation:Persistent organic pollutants (POP):Polycyclic aromatic hydrocarbons",
    15: "root:Engineered:Bioremediation:Persistent organic pollutants (POP)",
    14: "root:Engineered:Bioremediation:Metal",
    13: "root:Engineered:Bioremediation:Hydrocarbon:Benzene:Bioreactor",
    12: "root:Engineered:Bioremediation:Hydrocarbon:Benzene",
    11: "root:Engineered:Bioremediation:Hydrocarbon",
    10: "root:Engineered:Bioremediation",
    9: "root:Engineered:Bioreactor:Continuous culture:Marine sediment inoculum:Wadden Sea-Germany",
    8: "root:Engineered:Bioreactor:Continuous culture:Marine sediment inoculum",
    7: "root:Engineered:Bioreactor:Continuous culture:Marine intertidal flat sediment inoculum:Wadden Sea-Germany",
    6: "root:Engineered:Bioreactor:Continuous culture:Marine intertidal flat sediment inoculum",
    5: "root:Engineered:Bioreactor:Continuous culture",
    4: "root:Engineered:Bioreactor",
    3: "root:Engineered:Biogas plant:Wet fermentation",
    2: "root:Engineered:Biogas plant",
    1: "root:Engineered",
    0: "root",
}

BIOME_TO_ID = {value: key for key, value in BIOMES.items()}


class BiomeMatrix:
    """
    A class to create a matrix which contains the child, parent information for each biome id.

    Biomes are hierarchical and can have children and parents:
    root:Engineered is the child of root
    root:Engineered:Bioreactor is the parent of root:Engineered:Bioreactor:Continuous culture

    This class contains methods to quickly fetch the children or parents for a single biome id,
    or the unique children/parent ids for a list of biome ids.
    """

    def __init__(self, biome_mapping):
        """
        Initialize the BiomeMatrix with a biome mapping dictionary.

        Args:
            biome_mapping (dict): A dictionary mapping biome IDs to their corresponding levels.
        """
        keys = sorted(biome_mapping.keys())
        adjacency_matrix = pd.DataFrame(None, index=keys, columns=keys)

        def find_children(parent_key, parent_level):
            for key, level in biome_mapping.items():
                if level.startswith(parent_level) and level != parent_level:
                    adjacency_matrix.at[parent_key, key] = 1
                    find_children(key, level)

        for key, level in biome_mapping.items():
            find_children(key, level)

        self.adjacency_matrix = adjacency_matrix

    def get_children(self, biome_id):
        """
        Get the children of a given biome ID.

        Args:
            biome_id (int): The biome ID to retrieve children for.

        Returns:
            list: A list of biome IDs representing the children of the given biome ID.
        """
        return self.adjacency_matrix.loc[biome_id][self.adjacency_matrix.loc[biome_id] == 1].index.tolist()

    def get_parents(self, biome_id):
        """
        Get the parents of a given biome ID.

        Args:
            biome_id (int): The biome ID to retrieve parents for.

        Returns:
            list: A list of biome IDs representing the parents of the given biome ID.
        """
        return self.adjacency_matrix[biome_id][self.adjacency_matrix[biome_id] == 1].index.tolist()

    def get_unique_children(self, biome_ids):
        """
        Get the unique children of a list of biome IDs including the input biome IDs.

        Args:
            biome_ids (list): A list of biome IDs to retrieve unique children for.

        Returns:
            list: A list of unique biome IDs representing the children of the given biome IDs,
                  including the input biome IDs themselves.
        """
        children = set()
        for biome_id in biome_ids:
            children.update(self.get_children(biome_id))
        return children

    def get_unique_parents(self, biome_ids):
        """
        Get the unique parents of a list of biome IDs including the input biome IDs.

        Args:
            biome_ids (list): A list of biome IDs to retrieve unique parents for.

        Returns:
            list: A list of unique biome IDs representing the parents of the given biome IDs,
                  including the input biome IDs themselves.
        """
        parents = set()
        for biome_id in biome_ids:
            parents.update(self.get_parents(biome_id))
        return parents


BIOME_MATRIX = BiomeMatrix(BIOMES)
